addon-name: "Lib's TimePlayed"
addon-description: "tracks /played time across all characters"
urls:
  curseforge: "https://www.curseforge.com/wow/addons/libs-timeplayed"
  discord: "https://discord.gg/Qc9TRBv"
